name: Snyk Code Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/setup@master

      - name: Snyk Code Test (fail on high)
        run: snyk code test --severity-threshold=high --sarif-file-output=snyk-code.sarif
        env:
          SNYK_TOKEN: a1eb8b76-9f7f-4ff8-8fcb-e951abcdfa23

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif

      - name: Snyk Monitor (upload to Snyk portal)
        run: snyk monitor --project-name=dev-sast
        env:
          SNYK_TOKEN: a1eb8b76-9f7f-4ff8-8fcb-e951abcdfa23
          
