name: Snyk Code Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  snyk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - uses: snyk/actions/setup@master

      # 1. Run Snyk Code Test, but DO NOT fail the job immediately
      - name: Run Snyk Code Scan (capture output, no fail)
        run: |
          snyk code test \
            --sarif-file-output=snyk-code.sarif \
            --json-file-output=snyk-code.json \
            || echo "Snyk Code found issues"
        env:
          SNYK_TOKEN: a1eb8b76-9f7f-4ff8-8fcb-e951abcdfa23

      # 2. Upload SARIF to GitHub Code Scanning
      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code.sarif

      # 4. Rerun Snyk with fail threshold (this will now fail the job)
      - name: Fail if High Severity Found
        run: snyk code test --severity-threshold=high
        env:
          SNYK_TOKEN: a1eb8b76-9f7f-4ff8-8fcb-e951abcdfa23

          
